### ISSUE TITLE
Genes

### ISSUE THREAD

**Issue by psp515** [psp515/EvolutionGenerator#6]
- [x] SlightChangingGenotype
- [x] NormalGenotype
- [x] Genes
- [x] IGenes
- [ ] Tests

**Comment by Guccio163** [comment]
geny napisane, stawiam że SlightChangingGenotype = DiscouragedGenotype, testy do napisania później

**Comment by psp515** [comment]
zrób pull requesta

-- Edit --
zrobiłe PR wiec jak bedziesz teraz nastepną rzecz robił to pamietaj zeby zrobić nowego brancha z maina
